# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1026Sopt3rdSeminnar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1026Sopt3rdSeminnar

pod 'CHIPageControl', '~> 0.1.3'


end
